// 单词库，按分类
const flashcardData = [
    // 日常生活
    { category: "日常生活", word: "toothbrush", pronunciation: "/ˈtuːθbrʌʃ/", chinese: "牙刷" },
    { category: "日常生活", word: "towel", pronunciation: "/ˈtaʊəl/", chinese: "毛巾" },
    { category: "日常生活", word: "refrigerator", pronunciation: "/rɪˈfrɪdʒəreɪtər/", chinese: "冰箱" },
    { category: "日常生活", word: "microwave", pronunciation: "/ˈmaɪkrəweɪv/", chinese: "微波炉" },
    { category: "日常生活", word: "laundry", pronunciation: "/ˈlɔːndri/", chinese: "洗衣" },
    { category: "日常生活", word: "wallet", pronunciation: "/ˈwɒlɪt/", chinese: "钱包" },
    { category: "日常生活", word: "umbrella", pronunciation: "/ʌmˈbrelə/", chinese: "雨伞" },
    { category: "日常生活", word: "remote control", pronunciation: "/rɪˈmoʊt kənˈtroʊl/", chinese: "遥控器" },
    { category: "日常生活", word: "sofa", pronunciation: "/ˈsoʊfə/", chinese: "沙发" },
    { category: "日常生活", word: "lamp", pronunciation: "/læmp/", chinese: "台灯" },
    // 旅行游玩
    { category: "旅行游玩", word: "passport", pronunciation: "/ˈpæspɔːrt/", chinese: "护照" },
    { category: "旅行游玩", word: "luggage", pronunciation: "/ˈlʌɡɪdʒ/", chinese: "行李" },
    { category: "旅行游玩", word: "boarding pass", pronunciation: "/ˈbɔːrdɪŋ pæs/", chinese: "登机牌" },
    { category: "旅行游玩", word: "hotel", pronunciation: "/hoʊˈtel/", chinese: "酒店" },
    { category: "旅行游玩", word: "reservation", pronunciation: "/ˌrezərˈveɪʃn/", chinese: "预订" },
    { category: "旅行游玩", word: "tourist", pronunciation: "/ˈtʊrɪst/", chinese: "游客" },
    { category: "旅行游玩", word: "guide", pronunciation: "/ɡaɪd/", chinese: "导游" },
    { category: "旅行游玩", word: "scenic spot", pronunciation: "/ˈsiːnɪk spɑːt/", chinese: "景点" },
    { category: "旅行游玩", word: "souvenir", pronunciation: "/ˌsuːvəˈnɪr/", chinese: "纪念品" },
    { category: "旅行游玩", word: "itinerary", pronunciation: "/aɪˈtɪnəreri/", chinese: "行程" },
    // 商务工作
    { category: "商务工作", word: "meeting", pronunciation: "/ˈmiːtɪŋ/", chinese: "会议" },
    { category: "商务工作", word: "contract", pronunciation: "/ˈkɒntrækt/", chinese: "合同" },
    { category: "商务工作", word: "presentation", pronunciation: "/ˌprezənˈteɪʃn/", chinese: "演讲，汇报" },
    { category: "商务工作", word: "deadline", pronunciation: "/ˈdedlaɪn/", chinese: "截止日期" },
    { category: "商务工作", word: "colleague", pronunciation: "/ˈkɒliːɡ/", chinese: "同事" },
    { category: "商务工作", word: "project", pronunciation: "/ˈprɒdʒekt/", chinese: "项目" },
    { category: "商务工作", word: "conference", pronunciation: "/ˈkɒnfərəns/", chinese: "会议，大会" },
    { category: "商务工作", word: "negotiation", pronunciation: "/nɪˌɡoʊʃiˈeɪʃn/", chinese: "谈判" },
    { category: "商务工作", word: "report", pronunciation: "/rɪˈpɔːrt/", chinese: "报告" },
    { category: "商务工作", word: "salary", pronunciation: "/ˈsæləri/", chinese: "工资" },
    // 日常生活（扩充）
    { category: "日常生活", word: "broom", pronunciation: "/bruːm/", chinese: "扫帚" },
    { category: "日常生活", word: "blanket", pronunciation: "/ˈblæŋkɪt/", chinese: "毯子" },
    { category: "日常生活", word: "pillow", pronunciation: "/ˈpɪloʊ/", chinese: "枕头" },
    { category: "日常生活", word: "curtain", pronunciation: "/ˈkɜːrtn/", chinese: "窗帘" },
    { category: "日常生活", word: "mirror", pronunciation: "/ˈmɪrər/", chinese: "镜子" },
    { category: "日常生活", word: "scissors", pronunciation: "/ˈsɪzərz/", chinese: "剪刀" },
    { category: "日常生活", word: "comb", pronunciation: "/koʊm/", chinese: "梳子" },
    { category: "日常生活", word: "toothpaste", pronunciation: "/ˈtuːθpeɪst/", chinese: "牙膏" },
    { category: "日常生活", word: "shampoo", pronunciation: "/ʃæmˈpuː/", chinese: "洗发水" },
    { category: "日常生活", word: "soap", pronunciation: "/soʊp/", chinese: "肥皂" },
    { category: "日常生活", word: "bucket", pronunciation: "/ˈbʌkɪt/", chinese: "水桶" },
    { category: "日常生活", word: "mop", pronunciation: "/mɑːp/", chinese: "拖把" },
    { category: "日常生活", word: "stool", pronunciation: "/stuːl/", chinese: "凳子" },
    { category: "日常生活", word: "drawer", pronunciation: "/drɔːr/", chinese: "抽屉" },
    { category: "日常生活", word: "closet", pronunciation: "/ˈklɑːzɪt/", chinese: "衣橱" },
    { category: "日常生活", word: "hanger", pronunciation: "/ˈhæŋər/", chinese: "衣架" },
    { category: "日常生活", word: "fan", pronunciation: "/fæn/", chinese: "风扇" },
    { category: "日常生活", word: "air conditioner", pronunciation: "/ˈer kəndɪʃənər/", chinese: "空调" },
    { category: "日常生活", word: "heater", pronunciation: "/ˈhiːtər/", chinese: "加热器" },
    { category: "日常生活", word: "plug", pronunciation: "/plʌɡ/", chinese: "插头" },
    { category: "日常生活", word: "socket", pronunciation: "/ˈsɑːkɪt/", chinese: "插座" },
    { category: "日常生活", word: "switch", pronunciation: "/swɪtʃ/", chinese: "开关" },
    { category: "日常生活", word: "clock", pronunciation: "/klɑːk/", chinese: "时钟" },
    { category: "日常生活", word: "calendar", pronunciation: "/ˈkælɪndər/", chinese: "日历" },
    { category: "日常生活", word: "newspaper", pronunciation: "/ˈnuːzpeɪpər/", chinese: "报纸" },
    { category: "日常生活", word: "magazine", pronunciation: "/ˌmæɡəˈziːn/", chinese: "杂志" },
    { category: "日常生活", word: "remote", pronunciation: "/rɪˈmoʊt/", chinese: "遥控器" },
    { category: "日常生活", word: "key", pronunciation: "/kiː/", chinese: "钥匙" },
    { category: "日常生活", word: "door", pronunciation: "/dɔːr/", chinese: "门" },
    { category: "日常生活", word: "window", pronunciation: "/ˈwɪndoʊ/", chinese: "窗户" },
    { category: "日常生活", word: "floor", pronunciation: "/flɔːr/", chinese: "地板" },
    { category: "日常生活", word: "ceiling", pronunciation: "/ˈsiːlɪŋ/", chinese: "天花板" },
    { category: "日常生活", word: "wall", pronunciation: "/wɔːl/", chinese: "墙" },
    { category: "日常生活", word: "picture", pronunciation: "/ˈpɪktʃər/", chinese: "图片，画" },
    { category: "日常生活", word: "television", pronunciation: "/ˈtelɪvɪʒn/", chinese: "电视" },
    { category: "日常生活", word: "computer", pronunciation: "/kəmˈpjuːtər/", chinese: "电脑" },
    { category: "日常生活", word: "phone", pronunciation: "/foʊn/", chinese: "电话" },
    { category: "日常生活", word: "charger", pronunciation: "/ˈtʃɑːrdʒər/", chinese: "充电器" },
    { category: "日常生活", word: "bag", pronunciation: "/bæɡ/", chinese: "包" },
    { category: "日常生活", word: "box", pronunciation: "/bɑːks/", chinese: "盒子" },
    { category: "日常生活", word: "basket", pronunciation: "/ˈbæskɪt/", chinese: "篮子" },
    { category: "日常生活", word: "bottle", pronunciation: "/ˈbɑːtl/", chinese: "瓶子" },
    { category: "日常生活", word: "cup", pronunciation: "/kʌp/", chinese: "杯子" },
    { category: "日常生活", word: "plate", pronunciation: "/pleɪt/", chinese: "盘子" },
    { category: "日常生活", word: "bowl", pronunciation: "/boʊl/", chinese: "碗" },
    { category: "日常生活", word: "spoon", pronunciation: "/spuːn/", chinese: "勺子" },
    { category: "日常生活", word: "fork", pronunciation: "/fɔːrk/", chinese: "叉子" },
    { category: "日常生活", word: "knife", pronunciation: "/naɪf/", chinese: "刀" },
    { category: "日常生活", word: "chopsticks", pronunciation: "/ˈtʃɑːpstɪks/", chinese: "筷子" },
    { category: "日常生活", word: "pan", pronunciation: "/pæn/", chinese: "平底锅" },
    { category: "日常生活", word: "pot", pronunciation: "/pɑːt/", chinese: "锅" },
    { category: "日常生活", word: "stove", pronunciation: "/stoʊv/", chinese: "炉子" },
    { category: "日常生活", word: "microwave oven", pronunciation: "/ˈmaɪkrəweɪv ˈʌvən/", chinese: "微波炉" },
    { category: "日常生活", word: "refrigerator", pronunciation: "/rɪˈfrɪdʒəreɪtər/", chinese: "冰箱" },
    { category: "日常生活", word: "sink", pronunciation: "/sɪŋk/", chinese: "水槽" },
    { category: "日常生活", word: "faucet", pronunciation: "/ˈfɔːsɪt/", chinese: "水龙头" },
    { category: "日常生活", word: "toilet", pronunciation: "/ˈtɔɪlət/", chinese: "马桶" },
    { category: "日常生活", word: "shower", pronunciation: "/ˈʃaʊər/", chinese: "淋浴" },
    { category: "日常生活", word: "tissue", pronunciation: "/ˈtɪʃuː/", chinese: "纸巾" },
    { category: "日常生活", word: "napkin", pronunciation: "/ˈnæpkɪn/", chinese: "餐巾纸" },
    { category: "日常生活", word: "brush", pronunciation: "/brʌʃ/", chinese: "刷子" },
    { category: "日常生活", word: "detergent", pronunciation: "/dɪˈtɜːrdʒənt/", chinese: "洗涤剂" },
    { category: "日常生活", word: "garbage", pronunciation: "/ˈɡɑːrbɪdʒ/", chinese: "垃圾" },
    { category: "日常生活", word: "trash can", pronunciation: "/træʃ kæn/", chinese: "垃圾桶" },
    { category: "日常生活", word: "recycle bin", pronunciation: "/rɪˈsaɪkl bɪn/", chinese: "回收箱" },
    { category: "日常生活", word: "light", pronunciation: "/laɪt/", chinese: "灯" },
    { category: "日常生活", word: "power", pronunciation: "/ˈpaʊər/", chinese: "电源" },
    { category: "日常生活", word: "water", pronunciation: "/ˈwɔːtər/", chinese: "水" },
    { category: "日常生活", word: "rice", pronunciation: "/raɪs/", chinese: "米饭" },
    { category: "日常生活", word: "noodles", pronunciation: "/ˈnuːdlz/", chinese: "面条" },
    { category: "日常生活", word: "bread", pronunciation: "/bred/", chinese: "面包" },
    { category: "日常生活", word: "egg", pronunciation: "/eɡ/", chinese: "鸡蛋" },
    { category: "日常生活", word: "milk", pronunciation: "/mɪlk/", chinese: "牛奶" },
    { category: "日常生活", word: "fruit", pronunciation: "/fruːt/", chinese: "水果" },
    { category: "日常生活", word: "vegetable", pronunciation: "/ˈvedʒtəbl/", chinese: "蔬菜" },
    { category: "日常生活", word: "meat", pronunciation: "/miːt/", chinese: "肉" },
    { category: "日常生活", word: "fish", pronunciation: "/fɪʃ/", chinese: "鱼" },
    { category: "日常生活", word: "chicken", pronunciation: "/ˈtʃɪkɪn/", chinese: "鸡肉" },
    { category: "日常生活", word: "beef", pronunciation: "/biːf/", chinese: "牛肉" },
    { category: "日常生活", word: "pork", pronunciation: "/pɔːrk/", chinese: "猪肉" },
    { category: "日常生活", word: "salt", pronunciation: "/sɔːlt/", chinese: "盐" },
    { category: "日常生活", word: "sugar", pronunciation: "/ˈʃʊɡər/", chinese: "糖" },
    { category: "日常生活", word: "oil", pronunciation: "/ɔɪl/", chinese: "油" },
    { category: "日常生活", word: "pepper", pronunciation: "/ˈpepər/", chinese: "胡椒" },
    { category: "日常生活", word: "sauce", pronunciation: "/sɔːs/", chinese: "酱" },
    { category: "日常生活", word: "snack", pronunciation: "/snæk/", chinese: "零食" },
    { category: "日常生活", word: "ice cream", pronunciation: "/ˌaɪs ˈkriːm/", chinese: "冰淇淋" },
    { category: "日常生活", word: "juice", pronunciation: "/dʒuːs/", chinese: "果汁" },
    { category: "日常生活", word: "tea", pronunciation: "/tiː/", chinese: "茶" },
    { category: "日常生活", word: "coffee", pronunciation: "/ˈkɔːfi/", chinese: "咖啡" },
    { category: "日常生活", word: "wine", pronunciation: "/waɪn/", chinese: "葡萄酒" },
    { category: "日常生活", word: "beer", pronunciation: "/bɪr/", chinese: "啤酒" },
    { category: "日常生活", word: "cigarette", pronunciation: "/ˌsɪɡəˈret/", chinese: "香烟" },
    { category: "日常生活", word: "umbrella", pronunciation: "/ʌmˈbrelə/", chinese: "雨伞" },
    { category: "日常生活", word: "wallet", pronunciation: "/ˈwɒlɪt/", chinese: "钱包" },
    { category: "日常生活", word: "money", pronunciation: "/ˈmʌni/", chinese: "钱" },
    { category: "日常生活", word: "ticket", pronunciation: "/ˈtɪkɪt/", chinese: "票" },
    { category: "日常生活", word: "card", pronunciation: "/kɑːrd/", chinese: "卡片" },
    { category: "日常生活", word: "receipt", pronunciation: "/rɪˈsiːt/", chinese: "收据" },
    { category: "日常生活", word: "bill", pronunciation: "/bɪl/", chinese: "账单" },
    { category: "日常生活", word: "change", pronunciation: "/tʃeɪndʒ/", chinese: "零钱" },
    { category: "日常生活", word: "coin", pronunciation: "/kɔɪn/", chinese: "硬币" },
    { category: "日常生活", word: "credit card", pronunciation: "/ˈkredɪt kɑːrd/", chinese: "信用卡" },
    { category: "日常生活", word: "ID card", pronunciation: "/ˌaɪˈdiː kɑːrd/", chinese: "身份证" },
    { category: "日常生活", word: "passport", pronunciation: "/ˈpæspɔːrt/", chinese: "护照" },
    { category: "日常生活", word: "bag", pronunciation: "/bæɡ/", chinese: "包" },
    { category: "日常生活", word: "suitcase", pronunciation: "/ˈsuːtkeɪs/", chinese: "手提箱" },
    { category: "日常生活", word: "backpack", pronunciation: "/ˈbækpæk/", chinese: "背包" },
    { category: "日常生活", word: "umbrella", pronunciation: "/ʌmˈbrelə/", chinese: "雨伞" },
    { category: "日常生活", word: "watch", pronunciation: "/wɑːtʃ/", chinese: "手表" },
    { category: "日常生活", word: "glasses", pronunciation: "/ˈɡlæsɪz/", chinese: "眼镜" },
    { category: "日常生活", word: "ring", pronunciation: "/rɪŋ/", chinese: "戒指" },
    { category: "日常生活", word: "necklace", pronunciation: "/ˈnekləs/", chinese: "项链" },
    { category: "日常生活", word: "earring", pronunciation: "/ˈɪrɪŋ/", chinese: "耳环" },
    { category: "日常生活", word: "belt", pronunciation: "/belt/", chinese: "皮带" },
    { category: "日常生活", word: "hat", pronunciation: "/hæt/", chinese: "帽子" },
    { category: "日常生活", word: "cap", pronunciation: "/kæp/", chinese: "鸭舌帽" },
    { category: "日常生活", word: "scarf", pronunciation: "/skɑːrf/", chinese: "围巾" },
    { category: "日常生活", word: "glove", pronunciation: "/ɡlʌv/", chinese: "手套" },
    { category: "日常生活", word: "shoe", pronunciation: "/ʃuː/", chinese: "鞋" },
    { category: "日常生活", word: "sock", pronunciation: "/sɑːk/", chinese: "袜子" },
    { category: "日常生活", word: "shirt", pronunciation: "/ʃɜːrt/", chinese: "衬衫" },
    { category: "日常生活", word: "T-shirt", pronunciation: "/ˈtiː ʃɜːrt/", chinese: "T恤" },
    { category: "日常生活", word: "coat", pronunciation: "/koʊt/", chinese: "外套" },
    { category: "日常生活", word: "jacket", pronunciation: "/ˈdʒækɪt/", chinese: "夹克" },
    { category: "日常生活", word: "sweater", pronunciation: "/ˈswetər/", chinese: "毛衣" },
    { category: "日常生活", word: "dress", pronunciation: "/dres/", chinese: "连衣裙" },
    { category: "日常生活", word: "skirt", pronunciation: "/skɜːrt/", chinese: "裙子" },
    { category: "日常生活", word: "pants", pronunciation: "/pænts/", chinese: "裤子" },
    { category: "日常生活", word: "shorts", pronunciation: "/ʃɔːrts/", chinese: "短裤" },
    { category: "日常生活", word: "jeans", pronunciation: "/dʒiːnz/", chinese: "牛仔裤" },
    { category: "日常生活", word: "pajamas", pronunciation: "/pəˈdʒɑːməz/", chinese: "睡衣" },
    { category: "日常生活", word: "umbrella", pronunciation: "/ʌmˈbrelə/", chinese: "雨伞" },
    { category: "日常生活", word: "towel", pronunciation: "/ˈtaʊəl/", chinese: "毛巾" },
    { category: "日常生活", word: "toothbrush", pronunciation: "/ˈtuːθbrʌʃ/", chinese: "牙刷" },
    { category: "日常生活", word: "toothpaste", pronunciation: "/ˈtuːθpeɪst/", chinese: "牙膏" },
    { category: "日常生活", word: "soap", pronunciation: "/soʊp/", chinese: "肥皂" },
    { category: "日常生活", word: "shampoo", pronunciation: "/ʃæmˈpuː/", chinese: "洗发水" },
    { category: "日常生活", word: "conditioner", pronunciation: "/kənˈdɪʃənər/", chinese: "护发素" },
    { category: "日常生活", word: "mirror", pronunciation: "/ˈmɪrər/", chinese: "镜子" },
    { category: "日常生活", word: "comb", pronunciation: "/koʊm/", chinese: "梳子" },
    { category: "日常生活", word: "scissors", pronunciation: "/ˈsɪzərz/", chinese: "剪刀" },
    { category: "日常生活", word: "razor", pronunciation: "/ˈreɪzər/", chinese: "剃须刀" },
    { category: "日常生活", word: "nail clipper", pronunciation: "/neɪl ˈklɪpər/", chinese: "指甲刀" },
    { category: "日常生活", word: "tissue", pronunciation: "/ˈtɪʃuː/", chinese: "纸巾" },
    { category: "日常生活", word: "napkin", pronunciation: "/ˈnæpkɪn/", chinese: "餐巾纸" },
    { category: "日常生活", word: "broom", pronunciation: "/bruːm/", chinese: "扫帚" },
    { category: "日常生活", word: "mop", pronunciation: "/mɑːp/", chinese: "拖把" },
    { category: "日常生活", word: "bucket", pronunciation: "/ˈbʌkɪt/", chinese: "水桶" },
    { category: "日常生活", word: "detergent", pronunciation: "/dɪˈtɜːrdʒənt/", chinese: "洗涤剂" },
    { category: "日常生活", word: "garbage", pronunciation: "/ˈɡɑːrbɪdʒ/", chinese: "垃圾" },
    { category: "日常生活", word: "trash can", pronunciation: "/træʃ kæn/", chinese: "垃圾桶" },
    { category: "日常生活", word: "recycle bin", pronunciation: "/rɪˈsaɪkl bɪn/", chinese: "回收箱" },
    { category: "日常生活", word: "elevator", pronunciation: "/ˈelɪveɪtər/", chinese: "电梯" },
    { category: "日常生活", word: "stairs", pronunciation: "/sterz/", chinese: "楼梯" },
    { category: "日常生活", word: "corridor", pronunciation: "/ˈkɔːrɪdɔːr/", chinese: "走廊" },
    { category: "日常生活", word: "yard", pronunciation: "/jɑːrd/", chinese: "院子" },
    { category: "日常生活", word: "garden", pronunciation: "/ˈɡɑːrdn/", chinese: "花园" },
    { category: "日常生活", word: "park", pronunciation: "/pɑːrk/", chinese: "公园" },
    { category: "日常生活", word: "road", pronunciation: "/roʊd/", chinese: "道路" },
    { category: "日常生活", word: "street", pronunciation: "/striːt/", chinese: "街道" },
    { category: "日常生活", word: "bridge", pronunciation: "/brɪdʒ/", chinese: "桥" },
    { category: "日常生活", word: "car", pronunciation: "/kɑːr/", chinese: "汽车" },
    { category: "日常生活", word: "bus", pronunciation: "/bʌs/", chinese: "公交车" },
    { category: "日常生活", word: "bicycle", pronunciation: "/ˈbaɪsɪkl/", chinese: "自行车" },
    { category: "日常生活", word: "motorcycle", pronunciation: "/ˈmoʊtərsaɪkl/", chinese: "摩托车" },
    { category: "日常生活", word: "train", pronunciation: "/treɪn/", chinese: "火车" },
    { category: "日常生活", word: "subway", pronunciation: "/ˈsʌbweɪ/", chinese: "地铁" },
    { category: "日常生活", word: "taxi", pronunciation: "/ˈtæksi/", chinese: "出租车" },
    { category: "日常生活", word: "airplane", pronunciation: "/ˈerpleɪn/", chinese: "飞机" },
    { category: "日常生活", word: "ship", pronunciation: "/ʃɪp/", chinese: "轮船" },
    { category: "日常生活", word: "boat", pronunciation: "/boʊt/", chinese: "小船" },
    { category: "日常生活", word: "traffic light", pronunciation: "/ˈtræfɪk laɪt/", chinese: "红绿灯" },
    { category: "日常生活", word: "crosswalk", pronunciation: "/ˈkrɔːswɔːk/", chinese: "人行横道" },
    { category: "日常生活", word: "sidewalk", pronunciation: "/ˈsaɪdwɔːk/", chinese: "人行道" },
    { category: "日常生活", word: "corner", pronunciation: "/ˈkɔːrnər/", chinese: "拐角" },
    { category: "日常生活", word: "store", pronunciation: "/stɔːr/", chinese: "商店" },
    { category: "日常生活", word: "supermarket", pronunciation: "/ˈsuːpərmɑːrkɪt/", chinese: "超市" },
    { category: "日常生活", word: "mall", pronunciation: "/mɔːl/", chinese: "商场" },
    { category: "日常生活", word: "restaurant", pronunciation: "/ˈrestrɒnt/", chinese: "餐厅" },
    { category: "日常生活", word: "cafe", pronunciation: "/kæˈfeɪ/", chinese: "咖啡馆" },
    { category: "日常生活", word: "bar", pronunciation: "/bɑːr/", chinese: "酒吧" },
    { category: "日常生活", word: "hospital", pronunciation: "/ˈhɑːspɪtl/", chinese: "医院" },
    { category: "日常生活", word: "clinic", pronunciation: "/ˈklɪnɪk/", chinese: "诊所" },
    { category: "日常生活", word: "pharmacy", pronunciation: "/ˈfɑːrməsi/", chinese: "药店" },
    { category: "日常生活", word: "bank", pronunciation: "/bæŋk/", chinese: "银行" },
    { category: "日常生活", word: "post office", pronunciation: "/poʊst ˈɑːfɪs/", chinese: "邮局" },
    { category: "日常生活", word: "police station", pronunciation: "/pəˈliːs ˈsteɪʃn/", chinese: "警察局" },
    { category: "日常生活", word: "fire station", pronunciation: "/ˈfaɪər ˈsteɪʃn/", chinese: "消防局" },
    { category: "日常生活", word: "school", pronunciation: "/skuːl/", chinese: "学校" },
    { category: "日常生活", word: "library", pronunciation: "/ˈlaɪbreri/", chinese: "图书馆" },
    { category: "日常生活", word: "museum", pronunciation: "/mjuˈziːəm/", chinese: "博物馆" },
    { category: "日常生活", word: "zoo", pronunciation: "/zuː/", chinese: "动物园" },
    { category: "日常生活", word: "cinema", pronunciation: "/ˈsɪnəmə/", chinese: "电影院" },
    { category: "日常生活", word: "theater", pronunciation: "/ˈθiːətər/", chinese: "剧院" },
    { category: "日常生活", word: "hotel", pronunciation: "/hoʊˈtel/", chinese: "酒店" },
    { category: "日常生活", word: "apartment", pronunciation: "/əˈpɑːrtmənt/", chinese: "公寓" },
    { category: "日常生活", word: "house", pronunciation: "/haʊs/", chinese: "房子" },
    { category: "日常生活", word: "room", pronunciation: "/ruːm/", chinese: "房间" },
    { category: "日常生活", word: "kitchen", pronunciation: "/ˈkɪtʃɪn/", chinese: "厨房" },
    { category: "日常生活", word: "bathroom", pronunciation: "/ˈbæθruːm/", chinese: "浴室" },
    { category: "日常生活", word: "bedroom", pronunciation: "/ˈbedruːm/", chinese: "卧室" },
    { category: "日常生活", word: "living room", pronunciation: "/ˈlɪvɪŋ ruːm/", chinese: "客厅" },
    { category: "日常生活", word: "balcony", pronunciation: "/ˈbælkəni/", chinese: "阳台" },
    { category: "日常生活", word: "garage", pronunciation: "/ɡəˈrɑːʒ/", chinese: "车库" },
    { category: "日常生活", word: "basement", pronunciation: "/ˈbeɪsmənt/", chinese: "地下室" },
    { category: "日常生活", word: "roof", pronunciation: "/ruːf/", chinese: "屋顶" },
    { category: "日常生活", word: "window", pronunciation: "/ˈwɪndoʊ/", chinese: "窗户" },
    { category: "日常生活", word: "door", pronunciation: "/dɔːr/", chinese: "门" },
    { category: "日常生活", word: "floor", pronunciation: "/flɔːr/", chinese: "地板" },
    { category: "日常生活", word: "ceiling", pronunciation: "/ˈsiːlɪŋ/", chinese: "天花板" },
    { category: "日常生活", word: "wall", pronunciation: "/wɔːl/", chinese: "墙" },
    { category: "日常生活", word: "picture", pronunciation: "/ˈpɪktʃər/", chinese: "图片，画" },
    { category: "日常生活", word: "television", pronunciation: "/ˈtelɪvɪʒn/", chinese: "电视" },
    { category: "日常生活", word: "computer", pronunciation: "/kəmˈpjuːtər/", chinese: "电脑" },
    { category: "日常生活", word: "phone", pronunciation: "/foʊn/", chinese: "电话" },
    { category: "日常生活", word: "charger", pronunciation: "/ˈtʃɑːrdʒər/", chinese: "充电器" },
    { category: "日常生活", word: "remote control", pronunciation: "/rɪˈmoʊt kənˈtroʊl/", chinese: "遥控器" },
    { category: "日常生活", word: "sofa", pronunciation: "/ˈsoʊfə/", chinese: "沙发" },
    { category: "日常生活", word: "lamp", pronunciation: "/læmp/", chinese: "台灯" },
    // 旅行游玩（扩充，去重）
    { category: "旅行游玩", word: "ticket", pronunciation: "/ˈtɪkɪt/", chinese: "票" },
    { category: "旅行游玩", word: "map", pronunciation: "/mæp/", chinese: "地图" },
    { category: "旅行游玩", word: "camera", pronunciation: "/ˈkæmərə/", chinese: "相机" },
    { category: "旅行游玩", word: "guidebook", pronunciation: "/ˈɡaɪdbʊk/", chinese: "旅游指南" },
    { category: "旅行游玩", word: "sunscreen", pronunciation: "/ˈsʌnskriːn/", chinese: "防晒霜" },
    { category: "旅行游玩", word: "swimsuit", pronunciation: "/ˈswɪmsuːt/", chinese: "泳衣" },
    { category: "旅行游玩", word: "beach", pronunciation: "/biːtʃ/", chinese: "海滩" },
    { category: "旅行游玩", word: "mountain", pronunciation: "/ˈmaʊntn/", chinese: "山" },
    { category: "旅行游玩", word: "forest", pronunciation: "/ˈfɔːrɪst/", chinese: "森林" },
    { category: "旅行游玩", word: "lake", pronunciation: "/leɪk/", chinese: "湖" },
    { category: "旅行游玩", word: "river", pronunciation: "/ˈrɪvər/", chinese: "河流" },
    { category: "旅行游玩", word: "island", pronunciation: "/ˈaɪlənd/", chinese: "岛屿" },
    { category: "旅行游玩", word: "museum", pronunciation: "/mjuˈziːəm/", chinese: "博物馆" },
    { category: "旅行游玩", word: "temple", pronunciation: "/ˈtempl/", chinese: "寺庙" },
    { category: "旅行游玩", word: "church", pronunciation: "/tʃɜːrtʃ/", chinese: "教堂" },
    { category: "旅行游玩", word: "castle", pronunciation: "/ˈkæsl/", chinese: "城堡" },
    { category: "旅行游玩", word: "palace", pronunciation: "/ˈpælɪs/", chinese: "宫殿" },
    { category: "旅行游玩", word: "market", pronunciation: "/ˈmɑːrkɪt/", chinese: "市场" },
    { category: "旅行游玩", word: "shopping mall", pronunciation: "/ˈʃɑːpɪŋ mɔːl/", chinese: "购物中心" },
    { category: "旅行游玩", word: "restaurant", pronunciation: "/ˈrestrɒnt/", chinese: "餐厅" },
    { category: "旅行游玩", word: "cafe", pronunciation: "/kæˈfeɪ/", chinese: "咖啡馆" },
    { category: "旅行游玩", word: "bar", pronunciation: "/bɑːr/", chinese: "酒吧" },
    { category: "旅行游玩", word: "souvenir shop", pronunciation: "/ˌsuːvəˈnɪr ʃɑːp/", chinese: "纪念品店" },
    { category: "旅行游玩", word: "taxi", pronunciation: "/ˈtæksi/", chinese: "出租车" },
    { category: "旅行游玩", word: "bus", pronunciation: "/bʌs/", chinese: "公交车" },
    { category: "旅行游玩", word: "subway", pronunciation: "/ˈsʌbweɪ/", chinese: "地铁" },
    { category: "旅行游玩", word: "train", pronunciation: "/treɪn/", chinese: "火车" },
    { category: "旅行游玩", word: "airport", pronunciation: "/ˈerpɔːrt/", chinese: "机场" },
    { category: "旅行游玩", word: "station", pronunciation: "/ˈsteɪʃn/", chinese: "车站" },
    { category: "旅行游玩", word: "ferry", pronunciation: "/ˈferi/", chinese: "渡船" },
    { category: "旅行游玩", word: "cruise", pronunciation: "/kruːz/", chinese: "游轮" },
    { category: "旅行游玩", word: "passport control", pronunciation: "/ˈpæspɔːrt kənˈtroʊl/", chinese: "护照检查" },
    { category: "旅行游玩", word: "customs", pronunciation: "/ˈkʌstəmz/", chinese: "海关" },
    { category: "旅行游玩", word: "visa", pronunciation: "/ˈviːzə/", chinese: "签证" },
    { category: "旅行游玩", word: "emergency", pronunciation: "/ɪˈmɜːrdʒənsi/", chinese: "紧急情况" },
    { category: "旅行游玩", word: "police station", pronunciation: "/pəˈliːs ˈsteɪʃn/", chinese: "警察局" },
    { category: "旅行游玩", word: "hospital", pronunciation: "/ˈhɑːspɪtl/", chinese: "医院" },
    { category: "旅行游玩", word: "pharmacy", pronunciation: "/ˈfɑːrməsi/", chinese: "药店" },
    { category: "旅行游玩", word: "ambulance", pronunciation: "/ˈæmbjələns/", chinese: "救护车" },
    { category: "旅行游玩", word: "tour group", pronunciation: "/tʊr ɡruːp/", chinese: "旅游团" },
    { category: "旅行游玩", word: "travel agency", pronunciation: "/ˈtrævl ˈeɪdʒənsi/", chinese: "旅行社" },
    { category: "旅行游玩", word: "local", pronunciation: "/ˈloʊkl/", chinese: "当地人" },
    { category: "旅行游玩", word: "foreigner", pronunciation: "/ˈfɔːrənər/", chinese: "外国人" },
    { category: "旅行游玩", word: "adventure", pronunciation: "/ədˈventʃər/", chinese: "冒险" },
    { category: "旅行游玩", word: "explore", pronunciation: "/ɪkˈsplɔːr/", chinese: "探索" },
    { category: "旅行游玩", word: "reservation number", pronunciation: "/ˌrezərˈveɪʃn ˈnʌmbər/", chinese: "预订号" },
    { category: "旅行游玩", word: "check-in", pronunciation: "/ˈtʃek ɪn/", chinese: "办理入住" },
    { category: "旅行游玩", word: "check-out", pronunciation: "/ˈtʃek aʊt/", chinese: "退房" },
    { category: "旅行游玩", word: "single room", pronunciation: "/ˈsɪŋɡl ruːm/", chinese: "单人房" },
    { category: "旅行游玩", word: "double room", pronunciation: "/ˈdʌbl ruːm/", chinese: "双人房" },
    { category: "旅行游玩", word: "suite", pronunciation: "/swiːt/", chinese: "套房" },
    { category: "旅行游玩", word: "reception", pronunciation: "/rɪˈsepʃn/", chinese: "前台" },
    { category: "旅行游玩", word: "key card", pronunciation: "/kiː kɑːrd/", chinese: "房卡" },
    { category: "旅行游玩", word: "lobby", pronunciation: "/ˈlɑːbi/", chinese: "大堂" },
    { category: "旅行游玩", word: "elevator", pronunciation: "/ˈelɪveɪtər/", chinese: "电梯" },
    { category: "旅行游玩", word: "floor", pronunciation: "/flɔːr/", chinese: "楼层" },
    { category: "旅行游玩", word: "reservation form", pronunciation: "/ˌrezərˈveɪʃn fɔːrm/", chinese: "预订表" },
    { category: "旅行游玩", word: "breakfast", pronunciation: "/ˈbrekfəst/", chinese: "早餐" },
    { category: "旅行游玩", word: "lunch", pronunciation: "/lʌntʃ/", chinese: "午餐" },
    { category: "旅行游玩", word: "dinner", pronunciation: "/ˈdɪnər/", chinese: "晚餐" },
    { category: "旅行游玩", word: "buffet", pronunciation: "/bəˈfeɪ/", chinese: "自助餐" },
    { category: "旅行游玩", word: "menu", pronunciation: "/ˈmenjuː/", chinese: "菜单" },
    { category: "旅行游玩", word: "order", pronunciation: "/ˈɔːrdər/", chinese: "点餐" },
    { category: "旅行游玩", word: "bill", pronunciation: "/bɪl/", chinese: "账单" },
    { category: "旅行游玩", word: "tip", pronunciation: "/tɪp/", chinese: "小费" },
    { category: "旅行游玩", word: "waiter", pronunciation: "/ˈweɪtər/", chinese: "男服务员" },
    { category: "旅行游玩", word: "waitress", pronunciation: "/ˈweɪtrəs/", chinese: "女服务员" },
    { category: "旅行游玩", word: "reservation", pronunciation: "/ˌrezərˈveɪʃn/", chinese: "预订" },
    { category: "旅行游玩", word: "boarding gate", pronunciation: "/ˈbɔːrdɪŋ ɡeɪt/", chinese: "登机口" },
    { category: "旅行游玩", word: "boarding time", pronunciation: "/ˈbɔːrdɪŋ taɪm/", chinese: "登机时间" },
    { category: "旅行游玩", word: "departure", pronunciation: "/dɪˈpɑːrtʃər/", chinese: "出发" },
    { category: "旅行游玩", word: "arrival", pronunciation: "/əˈraɪvl/", chinese: "到达" },
    { category: "旅行游玩", word: "delay", pronunciation: "/dɪˈleɪ/", chinese: "延误" },
    { category: "旅行游玩", word: "cancel", pronunciation: "/ˈkænsl/", chinese: "取消" },
    { category: "旅行游玩", word: "information desk", pronunciation: "/ˌɪnfərˈmeɪʃn desk/", chinese: "问讯处" },
    { category: "旅行游玩", word: "tourist information", pronunciation: "/ˈtʊrɪst ˌɪnfərˈmeɪʃn/", chinese: "旅游信息" },
    { category: "旅行游玩", word: "emergency exit", pronunciation: "/ɪˈmɜːrdʒənsi ˈeɡzɪt/", chinese: "紧急出口" },
    { category: "旅行游玩", word: "fire escape", pronunciation: "/ˈfaɪər ɪˈskeɪp/", chinese: "消防通道" },
    { category: "旅行游玩", word: "lost and found", pronunciation: "/lɔːst ənd faʊnd/", chinese: "失物招领处" },
    { category: "旅行游玩", word: "locker", pronunciation: "/ˈlɑːkər/", chinese: "储物柜" },
    { category: "旅行游玩", word: "ATM", pronunciation: "/ˌeɪ tiː ˈem/", chinese: "自动取款机" },
    { category: "旅行游玩", word: "currency exchange", pronunciation: "/ˈkɜːrənsi ɪksˈtʃeɪndʒ/", chinese: "货币兑换" },
    { category: "旅行游玩", word: "weather", pronunciation: "/ˈweðər/", chinese: "天气" },
    { category: "旅行游玩", word: "temperature", pronunciation: "/ˈtemprətʃər/", chinese: "温度" },
    { category: "旅行游玩", word: "raincoat", pronunciation: "/ˈreɪnkoʊt/", chinese: "雨衣" },
    { category: "旅行游玩", word: "umbrella", pronunciation: "/ʌmˈbrelə/", chinese: "雨伞" },
    { category: "旅行游玩", word: "suitcase", pronunciation: "/ˈsuːtkeɪs/", chinese: "手提箱" },
    { category: "旅行游玩", word: "backpack", pronunciation: "/ˈbækpæk/", chinese: "背包" },
    { category: "旅行游玩", word: "luggage", pronunciation: "/ˈlʌɡɪdʒ/", chinese: "行李" },
    { category: "旅行游玩", word: "passport", pronunciation: "/ˈpæspɔːrt/", chinese: "护照" },
    { category: "旅行游玩", word: "ID card", pronunciation: "/ˌaɪˈdiː kɑːrd/", chinese: "身份证" },
    { category: "旅行游玩", word: "credit card", pronunciation: "/ˈkredɪt kɑːrd/", chinese: "信用卡" },
    { category: "旅行游玩", word: "money", pronunciation: "/ˈmʌni/", chinese: "钱" },
    { category: "旅行游玩", word: "change", pronunciation: "/tʃeɪndʒ/", chinese: "零钱" },
    { category: "旅行游玩", word: "coin", pronunciation: "/kɔɪn/", chinese: "硬币" },
    { category: "旅行游玩", word: "receipt", pronunciation: "/rɪˈsiːt/", chinese: "收据" },
    { category: "旅行游玩", word: "bill", pronunciation: "/bɪl/", chinese: "账单" },
    { category: "旅行游玩", word: "phone", pronunciation: "/foʊn/", chinese: "电话" },
    { category: "旅行游玩", word: "charger", pronunciation: "/ˈtʃɑːrdʒər/", chinese: "充电器" },
    { category: "旅行游玩", word: "adapter", pronunciation: "/əˈdæptər/", chinese: "转换插头" },
    { category: "旅行游玩", word: "battery", pronunciation: "/ˈbætəri/", chinese: "电池" },
    { category: "旅行游玩", word: "toothbrush", pronunciation: "/ˈtuːθbrʌʃ/", chinese: "牙刷" },
    { category: "旅行游玩", word: "towel", pronunciation: "/ˈtaʊəl/", chinese: "毛巾" },
    { category: "旅行游玩", word: "clothes", pronunciation: "/kloʊðz/", chinese: "衣服" },
    { category: "旅行游玩", word: "shoes", pronunciation: "/ʃuːz/", chinese: "鞋子" },
    { category: "旅行游玩", word: "hat", pronunciation: "/hæt/", chinese: "帽子" },
    { category: "旅行游玩", word: "sunglasses", pronunciation: "/ˈsʌnɡlæsɪz/", chinese: "太阳镜" },
    { category: "旅行游玩", word: "umbrella", pronunciation: "/ʌmˈbrelə/", chinese: "雨伞" },
    { category: "旅行游玩", word: "swimsuit", pronunciation: "/ˈswɪmsuːt/", chinese: "泳衣" },
    { category: "旅行游玩", word: "toiletries", pronunciation: "/ˈtɔɪlətriz/", chinese: "洗漱用品" },
    { category: "旅行游玩", word: "medicine", pronunciation: "/ˈmedɪsn/", chinese: "药品" },
    { category: "旅行游玩", word: "bandage", pronunciation: "/ˈbændɪdʒ/", chinese: "绷带" },
    { category: "旅行游玩", word: "first aid kit", pronunciation: "/ˌfɜːrst ˈeɪd kɪt/", chinese: "急救包" },
    { category: "旅行游玩", word: "snack", pronunciation: "/snæk/", chinese: "零食" },
    { category: "旅行游玩", word: "water", pronunciation: "/ˈwɔːtər/", chinese: "水" },
    { category: "旅行游玩", word: "fruit", pronunciation: "/fruːt/", chinese: "水果" },
    { category: "旅行游玩", word: "bread", pronunciation: "/bred/", chinese: "面包" },
    { category: "旅行游玩", word: "breakfast", pronunciation: "/ˈbrekfəst/", chinese: "早餐" },
    { category: "旅行游玩", word: "lunch", pronunciation: "/lʌntʃ/", chinese: "午餐" },
    { category: "旅行游玩", word: "dinner", pronunciation: "/ˈdɪnər/", chinese: "晚餐" },
    // 商务工作（批量扩充，查重去重，涵盖职位、办公、会议、财务、沟通、合同、项目、公司、行业、常用表达等）
    { category: "商务工作", word: "manager", pronunciation: "/ˈmænɪdʒər/", chinese: "经理" },
    { category: "商务工作", word: "assistant", pronunciation: "/əˈsɪstənt/", chinese: "助理" },
    { category: "商务工作", word: "secretary", pronunciation: "/ˈsekrəteri/", chinese: "秘书" },
    { category: "商务工作", word: "director", pronunciation: "/dəˈrektər/", chinese: "主管，董事" },
    { category: "商务工作", word: "president", pronunciation: "/ˈprezɪdənt/", chinese: "总裁" },
    { category: "商务工作", word: "CEO", pronunciation: "/ˌsiː iː ˈoʊ/", chinese: "首席执行官" },
    { category: "商务工作", word: "CFO", pronunciation: "/ˌsiː ef ˈoʊ/", chinese: "首席财务官" },
    { category: "商务工作", word: "CTO", pronunciation: "/ˌsiː tiː ˈoʊ/", chinese: "首席技术官" },
    { category: "商务工作", word: "employee", pronunciation: "/ɪmˈplɔɪiː/", chinese: "员工" },
    { category: "商务工作", word: "staff", pronunciation: "/stæf/", chinese: "职员" },
    { category: "商务工作", word: "intern", pronunciation: "/ˈɪntɜːrn/", chinese: "实习生" },
    { category: "商务工作", word: "department", pronunciation: "/dɪˈpɑːrtmənt/", chinese: "部门" },
    { category: "商务工作", word: "division", pronunciation: "/dɪˈvɪʒn/", chinese: "分部" },
    { category: "商务工作", word: "branch", pronunciation: "/bræntʃ/", chinese: "分公司" },
    { category: "商务工作", word: "subsidiary", pronunciation: "/səbˈsɪdiˌeri/", chinese: "子公司" },
    { category: "商务工作", word: "headquarters", pronunciation: "/ˈhedkwɔːrtərz/", chinese: "总部" },
    { category: "商务工作", word: "office", pronunciation: "/ˈɔːfɪs/", chinese: "办公室" },
    { category: "商务工作", word: "cubicle", pronunciation: "/ˈkjuːbɪkl/", chinese: "小隔间" },
    { category: "商务工作", word: "workspace", pronunciation: "/ˈwɜːrkˌspeɪs/", chinese: "工作区" },
    { category: "商务工作", word: "desk", pronunciation: "/desk/", chinese: "书桌" },
    { category: "商务工作", word: "chair", pronunciation: "/tʃer/", chinese: "椅子" },
    { category: "商务工作", word: "computer", pronunciation: "/kəmˈpjuːtər/", chinese: "电脑" },
    { category: "商务工作", word: "printer", pronunciation: "/ˈprɪntər/", chinese: "打印机" },
    { category: "商务工作", word: "scanner", pronunciation: "/ˈskænər/", chinese: "扫描仪" },
    { category: "商务工作", word: "copier", pronunciation: "/ˈkɑːpiər/", chinese: "复印机" },
    { category: "商务工作", word: "projector", pronunciation: "/prəˈdʒektər/", chinese: "投影仪" },
    { category: "商务工作", word: "whiteboard", pronunciation: "/ˈwaɪtbɔːrd/", chinese: "白板" },
    { category: "商务工作", word: "notebook", pronunciation: "/ˈnoʊtbʊk/", chinese: "笔记本" },
    { category: "商务工作", word: "pen", pronunciation: "/pen/", chinese: "钢笔" },
    { category: "商务工作", word: "pencil", pronunciation: "/ˈpensl/", chinese: "铅笔" },
    { category: "商务工作", word: "marker", pronunciation: "/ˈmɑːrkər/", chinese: "记号笔" },
    { category: "商务工作", word: "stapler", pronunciation: "/ˈsteɪplər/", chinese: "订书机" },
    { category: "商务工作", word: "paper clip", pronunciation: "/ˈpeɪpər klɪp/", chinese: "回形针" },
    { category: "商务工作", word: "envelope", pronunciation: "/ˈenvəloʊp/", chinese: "信封" },
    { category: "商务工作", word: "document", pronunciation: "/ˈdɑːkjumənt/", chinese: "文件" },
    { category: "商务工作", word: "file", pronunciation: "/faɪl/", chinese: "档案" },
    { category: "商务工作", word: "folder", pronunciation: "/ˈfoʊldər/", chinese: "文件夹" },
    { category: "商务工作", word: "report", pronunciation: "/rɪˈpɔːrt/", chinese: "报告" },
    { category: "商务工作", word: "proposal", pronunciation: "/prəˈpoʊzl/", chinese: "提案" },
    { category: "商务工作", word: "plan", pronunciation: "/plæn/", chinese: "计划" },
    { category: "商务工作", word: "schedule", pronunciation: "/ˈskedʒuːl/", chinese: "日程" },
    { category: "商务工作", word: "agenda", pronunciation: "/əˈdʒendə/", chinese: "议程" },
    { category: "商务工作", word: "minutes", pronunciation: "/ˈmɪnɪts/", chinese: "会议记录" },
    { category: "商务工作", word: "memo", pronunciation: "/ˈmemoʊ/", chinese: "备忘录" },
    { category: "商务工作", word: "notice", pronunciation: "/ˈnoʊtɪs/", chinese: "通知" },
    { category: "商务工作", word: "announcement", pronunciation: "/əˈnaʊnsmənt/", chinese: "公告" },
    { category: "商务工作", word: "newsletter", pronunciation: "/ˈnuːzˌletər/", chinese: "简报" },
    { category: "商务工作", word: "email", pronunciation: "/ˈiːmeɪl/", chinese: "电子邮件" },
    { category: "商务工作", word: "attachment", pronunciation: "/əˈtætʃmənt/", chinese: "附件" },
    { category: "商务工作", word: "signature", pronunciation: "/ˈsɪɡnətʃər/", chinese: "签名" },
    { category: "商务工作", word: "stamp", pronunciation: "/stæmp/", chinese: "印章" },
    { category: "商务工作", word: "seal", pronunciation: "/siːl/", chinese: "封条" },
    { category: "商务工作", word: "contract", pronunciation: "/ˈkɒntrækt/", chinese: "合同" },
    { category: "商务工作", word: "agreement", pronunciation: "/əˈɡriːmənt/", chinese: "协议" },
    { category: "商务工作", word: "deal", pronunciation: "/diːl/", chinese: "交易" },
    { category: "商务工作", word: "negotiation", pronunciation: "/nɪˌɡoʊʃiˈeɪʃn/", chinese: "谈判" },
    { category: "商务工作", word: "project", pronunciation: "/ˈprɒdʒekt/", chinese: "项目" },
    { category: "商务工作", word: "task", pronunciation: "/tæsk/", chinese: "任务" },
    { category: "商务工作", word: "assignment", pronunciation: "/əˈsaɪnmənt/", chinese: "分配，任务" },
    { category: "商务工作", word: "deadline", pronunciation: "/ˈdedlaɪn/", chinese: "截止日期" },
    { category: "商务工作", word: "milestone", pronunciation: "/ˈmaɪlstoʊn/", chinese: "里程碑" },
    { category: "商务工作", word: "progress", pronunciation: "/ˈprɑːɡres/", chinese: "进展" },
    { category: "商务工作", word: "goal", pronunciation: "/ɡoʊl/", chinese: "目标" },
    { category: "商务工作", word: "target", pronunciation: "/ˈtɑːrɡɪt/", chinese: "目标" },
    { category: "商务工作", word: "result", pronunciation: "/rɪˈzʌlt/", chinese: "结果" },
    { category: "商务工作", word: "success", pronunciation: "/səkˈses/", chinese: "成功" },
    { category: "商务工作", word: "failure", pronunciation: "/ˈfeɪljər/", chinese: "失败" },
    { category: "商务工作", word: "risk", pronunciation: "/rɪsk/", chinese: "风险" },
    { category: "商务工作", word: "opportunity", pronunciation: "/ˌɑːpərˈtuːnəti/", chinese: "机会" },
    { category: "商务工作", word: "challenge", pronunciation: "/ˈtʃælɪndʒ/", chinese: "挑战" },
    { category: "商务工作", word: "strategy", pronunciation: "/ˈstrætədʒi/", chinese: "策略" },
    { category: "商务工作", word: "plan", pronunciation: "/plæn/", chinese: "计划" },
    { category: "商务工作", word: "budget", pronunciation: "/ˈbʌdʒɪt/", chinese: "预算" },
    { category: "商务工作", word: "cost", pronunciation: "/kɔːst/", chinese: "成本" },
    { category: "商务工作", word: "expense", pronunciation: "/ɪkˈspens/", chinese: "支出" },
    { category: "商务工作", word: "income", pronunciation: "/ˈɪnkʌm/", chinese: "收入" },
    { category: "商务工作", word: "revenue", pronunciation: "/ˈrevənuː/", chinese: "营业额" },
    { category: "商务工作", word: "profit", pronunciation: "/ˈprɑːfɪt/", chinese: "利润" },
    { category: "商务工作", word: "loss", pronunciation: "/lɔːs/", chinese: "亏损" },
    { category: "商务工作", word: "invoice", pronunciation: "/ˈɪnvɔɪs/", chinese: "发票" },
    { category: "商务工作", word: "receipt", pronunciation: "/rɪˈsiːt/", chinese: "收据" },
    { category: "商务工作", word: "payment", pronunciation: "/ˈpeɪmənt/", chinese: "付款" },
    { category: "商务工作", word: "account", pronunciation: "/əˈkaʊnt/", chinese: "账户" },
    { category: "商务工作", word: "bank", pronunciation: "/bæŋk/", chinese: "银行" },
    { category: "商务工作", word: "loan", pronunciation: "/loʊn/", chinese: "贷款" },
    { category: "商务工作", word: "interest", pronunciation: "/ˈɪntrəst/", chinese: "利息" },
    { category: "商务工作", word: "tax", pronunciation: "/tæks/", chinese: "税" },
    { category: "商务工作", word: "finance", pronunciation: "/faɪˈnæns/", chinese: "金融，财务" },
    { category: "商务工作", word: "investment", pronunciation: "/ɪnˈvestmənt/", chinese: "投资" },
    { category: "商务工作", word: "stock", pronunciation: "/stɑːk/", chinese: "股票" },
    { category: "商务工作", word: "shareholder", pronunciation: "/ˈʃerhoʊldər/", chinese: "股东" },
    { category: "商务工作", word: "market", pronunciation: "/ˈmɑːrkɪt/", chinese: "市场" },
    { category: "商务工作", word: "industry", pronunciation: "/ˈɪndəstri/", chinese: "行业" },
    { category: "商务工作", word: "company", pronunciation: "/ˈkʌmpəni/", chinese: "公司" },
    { category: "商务工作", word: "corporation", pronunciation: "/ˌkɔːrpəˈreɪʃn/", chinese: "企业" },
    { category: "商务工作", word: "enterprise", pronunciation: "/ˈentərpraɪz/", chinese: "企业" },
    { category: "商务工作", word: "firm", pronunciation: "/fɜːrm/", chinese: "公司，事务所" },
    { category: "商务工作", word: "client", pronunciation: "/ˈklaɪənt/", chinese: "客户" },
    { category: "商务工作", word: "customer", pronunciation: "/ˈkʌstəmər/", chinese: "顾客" },
    { category: "商务工作", word: "supplier", pronunciation: "/səˈplaɪər/", chinese: "供应商" },
    { category: "商务工作", word: "partner", pronunciation: "/ˈpɑːrtnər/", chinese: "合作伙伴" },
    { category: "商务工作", word: "competitor", pronunciation: "/kəmˈpetɪtər/", chinese: "竞争对手" },
    { category: "商务工作", word: "market share", pronunciation: "/ˈmɑːrkɪt ʃer/", chinese: "市场份额" },
    { category: "商务工作", word: "brand", pronunciation: "/brænd/", chinese: "品牌" },
    { category: "商务工作", word: "product", pronunciation: "/ˈprɑːdʌkt/", chinese: "产品" },
    { category: "商务工作", word: "service", pronunciation: "/ˈsɜːrvɪs/", chinese: "服务" },
    { category: "商务工作", word: "order", pronunciation: "/ˈɔːrdər/", chinese: "订单" },
    { category: "商务工作", word: "shipment", pronunciation: "/ˈʃɪpmənt/", chinese: "发货" },
    { category: "商务工作", word: "delivery", pronunciation: "/dɪˈlɪvəri/", chinese: "交付" },
    { category: "商务工作", word: "purchase", pronunciation: "/ˈpɜːrtʃəs/", chinese: "采购" },
    { category: "商务工作", word: "supply", pronunciation: "/səˈplaɪ/", chinese: "供应" },
    { category: "商务工作", word: "demand", pronunciation: "/dɪˈmænd/", chinese: "需求" },
    { category: "商务工作", word: "inventory", pronunciation: "/ˈɪnvəntɔːri/", chinese: "库存" },
    { category: "商务工作", word: "stock", pronunciation: "/stɑːk/", chinese: "存货，股票" },
    { category: "商务工作", word: "warehouse", pronunciation: "/ˈwerhaʊs/", chinese: "仓库" },
    { category: "商务工作", word: "logistics", pronunciation: "/ləˈdʒɪstɪks/", chinese: "物流" },
    { category: "商务工作", word: "transportation", pronunciation: "/ˌtrænspərˈteɪʃn/", chinese: "运输" },
    { category: "商务工作", word: "export", pronunciation: "/ˈekspɔːrt/", chinese: "出口" },
    { category: "商务工作", word: "import", pronunciation: "/ˈɪmpɔːrt/", chinese: "进口" },
    { category: "商务工作", word: "trade", pronunciation: "/treɪd/", chinese: "贸易" },
    { category: "商务工作", word: "fair", pronunciation: "/fer/", chinese: "展会" },
    { category: "商务工作", word: "exhibition", pronunciation: "/ˌeksɪˈbɪʃn/", chinese: "展览" },
    { category: "商务工作", word: "conference", pronunciation: "/ˈkɒnfərəns/", chinese: "会议，大会" },
    { category: "商务工作", word: "seminar", pronunciation: "/ˈsemɪnɑːr/", chinese: "研讨会" },
    { category: "商务工作", word: "workshop", pronunciation: "/ˈwɜːrkʃɑːp/", chinese: "工作坊" },
    { category: "商务工作", word: "training", pronunciation: "/ˈtreɪnɪŋ/", chinese: "培训" },
    { category: "商务工作", word: "presentation", pronunciation: "/ˌprezənˈteɪʃn/", chinese: "演讲，汇报" },
    { category: "商务工作", word: "speech", pronunciation: "/spiːtʃ/", chinese: "演讲" },
    { category: "商务工作", word: "discussion", pronunciation: "/dɪˈskʌʃn/", chinese: "讨论" },
    { category: "商务工作", word: "negotiation", pronunciation: "/nɪˌɡoʊʃiˈeɪʃn/", chinese: "谈判" },
    { category: "商务工作", word: "debate", pronunciation: "/dɪˈbeɪt/", chinese: "辩论" },
    { category: "商务工作", word: "questionnaire", pronunciation: "/ˌkwestʃəˈner/", chinese: "问卷" },
    { category: "商务工作", word: "survey", pronunciation: "/ˈsɜːrveɪ/", chinese: "调查" },
    { category: "商务工作", word: "feedback", pronunciation: "/ˈfiːdbæk/", chinese: "反馈" },
    { category: "商务工作", word: "suggestion", pronunciation: "/səˈdʒestʃən/", chinese: "建议" },
    { category: "商务工作", word: "complaint", pronunciation: "/kəmˈpleɪnt/", chinese: "投诉" },
    { category: "商务工作", word: "problem", pronunciation: "/ˈprɑːbləm/", chinese: "问题" },
    { category: "商务工作", word: "solution", pronunciation: "/səˈluːʃn/", chinese: "解决方案" },
    { category: "商务工作", word: "support", pronunciation: "/səˈpɔːrt/", chinese: "支持" },
    { category: "商务工作", word: "service", pronunciation: "/ˈsɜːrvɪs/", chinese: "服务" }
];

window.flashcardData = flashcardData;
